services:
  # Сервис для базы данных MSSQL
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: currenter-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: